import { User } from '../types';

export const INITIAL_REGISTERED_APPLICANTS: any[] = [
  {
    id: "reg-kta-01",
    userId: "user-reg-muhamad-zakaria",
    nama: "Muhamad Zakaria",
    namaLengkap: "Muhamad Zakaria",
    email: "muhamad.zakaria@hw.or.id",
    noWa: "081234875501",
    noHp: "081234875501",
    asalDaerah: "Kabupaten Banjarnegara",
    asalKwarda: "Kabupaten Banjarnegara",
    qabilah: "Qabilah Banjarnegara",
    tingkatan: "Penghela",
    golongan: "Penghela",
    jenisKelamin: "L",
    tempatLahir: "Banjarnegara",
    tanggalLahir: "2006-05-14",
    alamat: "Jl. Raya Banjarnegara No. 12, Banjarnegara",
    status: "pending",
    statusKta: "pending",
    statusPembayaran: "Belum Bayar",
    statusAktivasi: "Belum Aktif",
    isVerified: false,
    jenisKta: "Digital",
    role: "umum",
    roles: ["umum"],
    activeRole: "umum",
    sourceType: "Pendaftaran KTA",
    tanggalAjuan: "2026-09-24T10:00:00.000Z",
    createdAt: "2026-09-24T10:00:00.000Z"
  },
  {
    id: "reg-kta-02",
    userId: "user-reg-rovu-audhika",
    nama: "Rovu Audhika Zyan Firdaus",
    namaLengkap: "Rovu Audhika Zyan Firdaus",
    email: "rovu.audhika@hw.or.id",
    noWa: "081234875502",
    noHp: "081234875502",
    asalDaerah: "Kabupaten Banyumas",
    asalKwarda: "Kabupaten Banyumas",
    qabilah: "Qabilah Banyumas",
    tingkatan: "Penghela",
    golongan: "Penghela",
    jenisKelamin: "L",
    tempatLahir: "Banyumas",
    tanggalLahir: "2007-08-20",
    alamat: "Jl. Jenderal Sudirman No. 45, Purwokerto",
    status: "pending",
    statusKta: "pending",
    statusPembayaran: "Belum Bayar",
    statusAktivasi: "Belum Aktif",
    isVerified: false,
    jenisKta: "Digital",
    role: "umum",
    roles: ["umum"],
    activeRole: "umum",
    sourceType: "Pendaftaran KTA",
    tanggalAjuan: "2026-09-24T10:05:00.000Z",
    createdAt: "2026-09-24T10:05:00.000Z"
  },
  {
    id: "reg-kta-03",
    userId: "user-reg-hudan-muutaqien",
    nama: "Hudan Muutaqien",
    namaLengkap: "Hudan Muutaqien",
    email: "hudan.muutaqien@hw.or.id",
    noWa: "081234875503",
    noHp: "081234875503",
    asalDaerah: "Kabupaten Wonosobo",
    asalKwarda: "Kabupaten Wonosobo",
    qabilah: "Qabilah Wonosobo",
    tingkatan: "Pengenal",
    golongan: "Pengenal",
    jenisKelamin: "L",
    tempatLahir: "Wonosobo",
    tanggalLahir: "2008-03-12",
    alamat: "Jl. Dieng Km. 4, Wonosobo",
    status: "pending",
    statusKta: "pending",
    statusPembayaran: "Belum Bayar",
    statusAktivasi: "Belum Aktif",
    isVerified: false,
    jenisKta: "Digital",
    role: "umum",
    roles: ["umum"],
    activeRole: "umum",
    sourceType: "Pendaftaran KTA",
    tanggalAjuan: "2026-09-24T10:10:00.000Z",
    createdAt: "2026-09-24T10:10:00.000Z"
  },
  {
    id: "reg-kta-04",
    userId: "user-reg-akbar-mubarok",
    nama: "Muhammad Akbar Mubarok",
    namaLengkap: "Muhammad Akbar Mubarok",
    email: "akbar.mubarok@hw.or.id",
    noWa: "081234875504",
    noHp: "081234875504",
    asalDaerah: "Kabupaten Kendal",
    asalKwarda: "Kabupaten Kendal",
    qabilah: "Qabilah Kendal",
    tingkatan: "Penghela",
    golongan: "Penghela",
    jenisKelamin: "L",
    tempatLahir: "Kendal",
    tanggalLahir: "2006-11-25",
    alamat: "Jl. Pemuda No. 88, Kendal",
    status: "pending",
    statusKta: "pending",
    statusPembayaran: "Belum Bayar",
    statusAktivasi: "Belum Aktif",
    isVerified: false,
    jenisKta: "Digital",
    role: "umum",
    roles: ["umum"],
    activeRole: "umum",
    sourceType: "Pendaftaran KTA",
    tanggalAjuan: "2026-09-24T10:15:00.000Z",
    createdAt: "2026-09-24T10:15:00.000Z"
  },
  {
    id: "reg-kta-05",
    userId: "user-reg-el-rozy",
    nama: "Abdullah El Rozy Al Buchury",
    namaLengkap: "Abdullah El Rozy Al Buchury",
    email: "abdullah.rozy@hw.or.id",
    noWa: "081234875505",
    noHp: "081234875505",
    asalDaerah: "Kabupaten Kudus",
    asalKwarda: "Kabupaten Kudus",
    qabilah: "Qabilah Kudus",
    tingkatan: "Pengenal",
    golongan: "Pengenal",
    jenisKelamin: "L",
    tempatLahir: "Kudus",
    tanggalLahir: "2008-09-09",
    alamat: "Jl. Sunan Kudus No. 19, Kudus",
    status: "pending",
    statusKta: "pending",
    statusPembayaran: "Belum Bayar",
    statusAktivasi: "Belum Aktif",
    isVerified: false,
    jenisKta: "Digital",
    role: "umum",
    roles: ["umum"],
    activeRole: "umum",
    sourceType: "Pendaftaran KTA",
    tanggalAjuan: "2026-09-24T10:20:00.000Z",
    createdAt: "2026-09-24T10:20:00.000Z"
  },
  {
    id: "reg-kta-06",
    userId: "user-reg-ibnu-alwi",
    nama: "Ibnu Alwi Tsaqib",
    namaLengkap: "Ibnu Alwi Tsaqib",
    email: "ibnu.alwi@hw.or.id",
    noWa: "081234875506",
    noHp: "081234875506",
    asalDaerah: "Kabupaten Wonosobo",
    asalKwarda: "Kabupaten Wonosobo",
    qabilah: "Qabilah Wonosobo",
    tingkatan: "Pengenal",
    golongan: "Pengenal",
    jenisKelamin: "L",
    tempatLahir: "Wonosobo",
    tanggalLahir: "2009-01-17",
    alamat: "Tanon RT 01/RW 06, Tanjunganom, Kepil, Wonosobo",
    status: "pending",
    statusKta: "pending",
    statusPembayaran: "Belum Bayar",
    statusAktivasi: "Belum Aktif",
    isVerified: false,
    jenisKta: "Digital",
    role: "umum",
    roles: ["umum"],
    activeRole: "umum",
    sourceType: "Pendaftaran KTA",
    tanggalAjuan: "2026-09-24T10:25:00.000Z",
    createdAt: "2026-09-24T10:25:00.000Z"
  },
  {
    id: "reg-kta-07",
    userId: "user-reg-enggar-astaghfarka",
    nama: "Enggar Astaghfarka Manahiro",
    namaLengkap: "Enggar Astaghfarka Manahiro",
    email: "enggar.astaghfarka@hw.or.id",
    noWa: "081234875507",
    noHp: "081234875507",
    asalDaerah: "Kota Magelang",
    asalKwarda: "Kota Magelang",
    qabilah: "Qabilah Kota Magelang",
    tingkatan: "Penghela",
    golongan: "Penghela",
    jenisKelamin: "L",
    tempatLahir: "Magelang",
    tanggalLahir: "2007-04-03",
    alamat: "Jl. Tidar No. 56, Magelang",
    status: "pending",
    statusKta: "pending",
    statusPembayaran: "Belum Bayar",
    statusAktivasi: "Belum Aktif",
    isVerified: false,
    jenisKta: "Digital",
    role: "umum",
    roles: ["umum"],
    activeRole: "umum",
    sourceType: "Pendaftaran KTA",
    tanggalAjuan: "2026-09-24T10:30:00.000Z",
    createdAt: "2026-09-24T10:30:00.000Z"
  },
  {
    id: "reg-kta-08",
    userId: "user-reg-vanquish-zidan",
    nama: "Vanquish Muhammad Zidan",
    namaLengkap: "Vanquish Muhammad Zidan",
    email: "vanquish.zidan@hw.or.id",
    noWa: "081234875508",
    noHp: "081234875508",
    asalDaerah: "Kabupaten Batang",
    asalKwarda: "Kabupaten Batang",
    qabilah: "Qabilah Batang",
    tingkatan: "Pengenal",
    golongan: "Pengenal",
    jenisKelamin: "L",
    tempatLahir: "Batang",
    tanggalLahir: "2008-12-10",
    alamat: "Jl. Jenderal Sudirman No. 102, Batang",
    status: "pending",
    statusKta: "pending",
    statusPembayaran: "Belum Bayar",
    statusAktivasi: "Belum Aktif",
    isVerified: false,
    jenisKta: "Digital",
    role: "umum",
    roles: ["umum"],
    activeRole: "umum",
    sourceType: "Pendaftaran KTA",
    tanggalAjuan: "2026-09-24T10:35:00.000Z",
    createdAt: "2026-09-24T10:35:00.000Z"
  },
  {
    id: "reg-kta-09",
    userId: "user-reg-alif-rezananda",
    nama: "Alif Rezananda Syah Putra",
    namaLengkap: "Alif Rezananda Syah Putra",
    email: "alif.rezananda@hw.or.id",
    noWa: "081234875509",
    noHp: "081234875509",
    asalDaerah: "Kabupaten Magelang",
    asalKwarda: "Kabupaten Magelang",
    qabilah: "Qabilah Magelang",
    tingkatan: "Penghela",
    golongan: "Penghela",
    jenisKelamin: "L",
    tempatLahir: "Magelang",
    tanggalLahir: "2006-07-22",
    alamat: "Muntilan, Magelang, Jawa Tengah",
    status: "pending",
    statusKta: "pending",
    statusPembayaran: "Belum Bayar",
    statusAktivasi: "Belum Aktif",
    isVerified: false,
    jenisKta: "Digital",
    role: "umum",
    roles: ["umum"],
    activeRole: "umum",
    sourceType: "Pendaftaran KTA",
    tanggalAjuan: "2026-09-24T10:40:00.000Z",
    createdAt: "2026-09-24T10:40:00.000Z"
  },
  {
    id: "reg-kta-10",
    userId: "user-reg-kamal-maulana",
    nama: "Kamal Maulana",
    namaLengkap: "Kamal Maulana",
    email: "kamal.maulana@hw.or.id",
    noWa: "081234875510",
    noHp: "081234875510",
    asalDaerah: "Kabupaten Klaten",
    asalKwarda: "Kabupaten Klaten",
    qabilah: "Qabilah Klaten",
    tingkatan: "Penghela",
    golongan: "Penghela",
    jenisKelamin: "L",
    tempatLahir: "Klaten",
    tanggalLahir: "2007-02-18",
    alamat: "Jl. Pemuda No. 23, Klaten",
    status: "pending",
    statusKta: "pending",
    statusPembayaran: "Belum Bayar",
    statusAktivasi: "Belum Aktif",
    isVerified: false,
    jenisKta: "Digital",
    role: "umum",
    roles: ["umum"],
    activeRole: "umum",
    sourceType: "Pendaftaran KTA",
    tanggalAjuan: "2026-09-24T10:45:00.000Z",
    createdAt: "2026-09-24T10:45:00.000Z"
  },
  {
    id: "reg-kta-11",
    userId: "user-reg-faisal-dzulfikar",
    nama: "Faisal Dzulfikar Al Abqori",
    namaLengkap: "Faisal Dzulfikar Al Abqori",
    email: "faisal.dzulfikar@hw.or.id",
    noWa: "081234875511",
    noHp: "081234875511",
    asalDaerah: "Kabupaten Kebumen",
    asalKwarda: "Kabupaten Kebumen",
    qabilah: "Qabilah Kebumen",
    tingkatan: "Pengenal",
    golongan: "Pengenal",
    jenisKelamin: "L",
    tempatLahir: "Kebumen",
    tanggalLahir: "2008-10-30",
    alamat: "Jl. Pahlawan No. 71, Kebumen",
    status: "pending",
    statusKta: "pending",
    statusPembayaran: "Belum Bayar",
    statusAktivasi: "Belum Aktif",
    isVerified: false,
    jenisKta: "Digital",
    role: "umum",
    roles: ["umum"],
    activeRole: "umum",
    sourceType: "Pendaftaran KTA",
    tanggalAjuan: "2026-09-24T10:50:00.000Z",
    createdAt: "2026-09-24T10:50:00.000Z"
  },
  {
    id: "reg-kta-12",
    userId: "user-reg-abdullah-sholih",
    nama: "Abdullah Sholih Asysyujaa'",
    namaLengkap: "Abdullah Sholih Asysyujaa'",
    email: "abdullah.sholih@hw.or.id",
    noWa: "081234875512",
    noHp: "081234875512",
    asalDaerah: "Kota Semarang",
    asalKwarda: "Kota Semarang",
    qabilah: "Qabilah Kota Semarang",
    tingkatan: "Penghela",
    golongan: "Penghela",
    jenisKelamin: "L",
    tempatLahir: "Semarang",
    tanggalLahir: "2006-12-05",
    alamat: "Jl. Pandanaran No. 80, Semarang",
    status: "pending",
    statusKta: "pending",
    statusPembayaran: "Belum Bayar",
    statusAktivasi: "Belum Aktif",
    isVerified: false,
    jenisKta: "Digital",
    role: "umum",
    roles: ["umum"],
    activeRole: "umum",
    sourceType: "Pendaftaran KTA",
    tanggalAjuan: "2026-09-24T10:55:00.000Z",
    createdAt: "2026-09-24T10:55:00.000Z"
  }
];

export const getRegisteredApplicantsAsUsers = (): User[] => {
  return INITIAL_REGISTERED_APPLICANTS.map(app => ({
    id: app.userId,
    email: app.email,
    password: "12345hw",
    namaLengkap: app.namaLengkap,
    nama: app.namaLengkap,
    jenisKelamin: app.jenisKelamin,
    tempatLahir: app.tempatLahir,
    tanggalLahir: app.tanggalLahir,
    alamat: app.alamat,
    noHp: app.noWa,
    asalKwarda: app.asalKwarda,
    qabilah: app.qabilah,
    golongan: app.tingkatan,
    tingkatan: app.tingkatan,
    role: "umum",
    roles: ["umum"],
    activeRole: "umum",
    pelatihan: [],
    pendidikan: "SMA/SMK",
    sosmed: "",
    isVerified: Boolean(app.isVerified),
    status: app.status || "pending",
    statusKta: app.statusKta || app.status || "pending",
    statusAktivasi: app.statusAktivasi || (app.isVerified ? "Aktif" : "Belum Aktif"),
    statusPembayaran: app.statusPembayaran || (app.isVerified ? "Lunas" : "Belum Bayar"),
    jenisKta: app.jenisKta,
    ktaNumber: app.ktaNumber || app.nomorKTA || "",
    nomorKTA: app.nomorKTA || app.ktaNumber || "",
    tanggalAjuan: app.tanggalAjuan,
    createdAt: app.createdAt
  }));
};

export const updateRegisteredApplicantStatus = (idOrEmail: string, status: string, ktaNumber?: string) => {
  const norm = (idOrEmail || '').toLowerCase().trim();
  const found = INITIAL_REGISTERED_APPLICANTS.find(a => 
    String(a.id).toLowerCase() === norm ||
    String(a.userId).toLowerCase() === norm ||
    (a.email && a.email.toLowerCase().trim() === norm) ||
    (a.nama && a.nama.toLowerCase().trim() === norm) ||
    (a.namaLengkap && a.namaLengkap.toLowerCase().trim() === norm)
  );
  if (found) {
    found.status = status;
    found.statusKta = status;
    if (status === 'approved') {
      found.isVerified = true;
      found.statusAktivasi = 'Aktif';
      found.statusPembayaran = 'Lunas';
      if (ktaNumber) {
        found.nomorKTA = ktaNumber;
        found.ktaNumber = ktaNumber;
      }
    }
  }
};
